project_name: "maternity_to_cml"
path_to_maternity_data: "data_in/mbrrace_test.csv"
output_dir: ""
log_dir: ""
dimensions: &dimensions
  - AgeAtBookingMotherAvg
  - AgeAtBookingMotherGroup
  - ApgarScore5TermGroup7
  - BabyFirstFeedBreastMilkStatus
  - BirthweightTermGroup
  - BirthweightTermGroup2500
  - CCP_Antenatal
  - CCP_Any_Pathways
  - CCP_Birth
  - CCP_Postpartum
  - CO_Concentration_Delivery
  - ComplexSocialFactorsInd
  - DeliveryMethodBabyGroup
  - DeprivationDecileAtBooking
  - EthnicCategoryMotherGroup
  - FolicAcidSupplement
  - GestAgeFormalAntenatalBookingGroup
  - GestationLengthBirth
  - GestationLengthBirthGroup37
  - PCP_Antenatal
  - PCP_Any_Pathways
  - PCP_Birth
  - PCP_Postpartum
  - PlaceTypeActualDeliveryMidwifery
  - PreviousCaesareanSectionsGroup
  - PreviousLiveBirthsGroup
  - SkinToSkinContact1HourTerm
  - SmokingStatusGroupBooking
  - TotalBabies
  - TotalBookings
  - TotalDeliveries
processing_funcs:
  - name: move_attributes_to_new_dimension
    params:
      source_col_name: "Org_Code"
      source_col_fill_value: "england"
      new_col_name: "mbrrace_grouping"
      new_col_fill_value: "no_mbrrace_grouping_filter"
      attributes_to_move:
        - "Group 1. Level 3 NICU & NS"
        - "Group 2. Level 3 NICU"
        - "Group 3. 4,000 or more"
        - "Group 4. 2,000 - 3,999"
        - "Group 5. Under 2,000"
  - name: replace_col_values
    params:
      col_name: "Org_Code"
      value_mappings:
        ALL: "england"
  # - name: concat_cols
  #   params:
  #     new_col_name: "dimension_cohort_id"
  #     cols_to_concat: *dimensions
  #     prefix: "all_"
  - name: rename_cols
    params:
      col_name_mappings:
        Org_code: "location_id"
        Org_level: "location_type"
        Final_value: "metric_value"
        ReportingPeriodStartDate: "reporting_period_start_datetime"
        ReportingPeriodEndDate: "last_record_timestamp"
  - name: cast_date_col_to_timestamp
    params:
      col_name: reporting_period_start_datetime
  - name: cast_date_col_to_timestamp
    params:
      col_name: last_record_timestamp
  - name: create_uuid_col
    params:
      col_name: "datapoint_id"
      length: 32

