project_name: "maternity_to_cml"
publication_date: &publication_date "01/12/2026"
last_ingest_timestamp: &last_ingest_timestamp "15/12/2026"
path_to_source_data: "data_in/msds-sep2025-exp-data.csv"
output_dir: "data_out"
status: "final"
log_dir: "logs/"
dimensions: &dimensions
  - mbrrace_grouping
  - AgeAtBookingMotherAvg
  - AgeAtBookingMotherGroup
  - ApgarScore5TermGroup7
  - BabyFirstFeedBreastMilkStatus
  - BirthweightTermGroup
  - BirthweightTermGroup2500
  - CCP_Antenatal
  - CCP_Any_Pathways
  - CCP_Birth
  - CCP_Postpartum
  - CO_Concentration_Delivery
  - ComplexSocialFactorsInd
  - DeliveryMethodBabyGroup
  - DeprivationDecileAtBooking
  - EthnicCategoryMotherGroup
  - FolicAcidSupplement
  - GestAgeFormalAntenatalBookingGroup
  - GestationLengthBirth
  - GestationLengthBirthGroup37
  - PCP_Antenatal
  - PCP_Any_Pathways
  - PCP_Birth
  - PCP_Postpartum
  - PlaceTypeActualDeliveryMidwifery
  - PreviousCaesareanSectionsGroup
  - PreviousLiveBirthsGroup
  - SkinToSkinContact1HourTerm
  - SmokingStatusGroupBooking
  - TotalBabies
  - TotalBookings
  - TotalDeliveries
dimension_creation_exclusions:
  - mbrrace_grouping
metric_id_replacements:
  AgeAtBookingMotherAvg_Average_over_women_act: MSMS0001_act
  AgeAtBookingMotherAvg_Average_over_women_prov: MSMS0001_prov
  AgeAtBookingMotherGroup_Women_act: MSMS0002_act
  AgeAtBookingMotherGroup_Women_prov: MSMS0002_prov
  BabyFirstFeedBreastMilkStatus_Babies_act: MSMS0003_act
  BabyFirstFeedBreastMilkStatus_Babies_prov: MSMS0003_prov
  CCP_Any_Pathways_Women_act: MSMS0004_act
  CCP_Any_Pathways_Women_prov: MSMS0004_prov
  CCP_Antenatal_Women_act: MSMS0005_act
  CCP_Antenatal_Women_prov: MSMS0005_prov
  CCP_Birth_Women_act: MSMS0006_act
  CCP_Birth_Women_prov: MSMS0006_prov
  CCP_Postpartum_Women_act: MSMS0007_act
  CCP_Postpartum_Women_prov: MSMS0007_prov
  ComplexSocialFactorsInd_Women_act: MSMS0008_act
  ComplexSocialFactorsInd_Women_prov: MSMS0008_prov
  DeliveryMethodBabyGroup_Women_act: MSMS0009_act
  DeliveryMethodBabyGroup_Women_prov: MSMS0009_prov
  DeprivationDecileAtBooking_Women_act: MSMS0010_act
  DeprivationDecileAtBooking_Women_prov: MSMS0010_prov
  EthnicCategoryMotherGroup_Women_act: MSMS0011_act
  EthnicCategoryMotherGroup_Women_prov: MSMS0011_prov
  FolicAcidSupplement_Women_act: MSMS0012_act
  FolicAcidSupplement_Women_prov: MSMS0012_prov
  GestAgeFormalAntenatalBookingGroup_Women_act: MSMS0013_act
  GestAgeFormalAntenatalBookingGroup_Women_prov: MSMS0013_prov
  GestationLengthBirth_Babies_act: MSMS0014_act
  GestationLengthBirth_Babies_prov: MSMS0014_prov
  GestationLengthBirthGroup37_Babies_act: MSMS0015_act
  GestationLengthBirthGroup37_Babies_prov: MSMS0015_prov
  PCP_Any_Pathways_Women_act: MSMS0016_act
  PCP_Any_Pathways_Women_prov: MSMS0016_prov
  PCP_Antenatal_Women_act: MSMS0017_act
  PCP_Antenatal_Women_prov: MSMS0017_prov
  PCP_Birth_Women_act: MSMS0018_act
  PCP_Birth_Women_prov: MSMS0018_prov
  PCP_Postpartum_Women_act: MSMS0019_act
  PCP_Postpartum_Women_prov: MSMS0019_prov
  PlaceTypeActualDeliveryMidwifery_Babies_act: MSMS0020_act
  PlaceTypeActualDeliveryMidwifery_Babies_prov: MSMS0020_prov
  PreviousCaesareanSectionsGroup_Women_act: MSMS0021_act
  PreviousCaesareanSectionsGroup_Women_prov: MSMS0021_prov
  PreviousLiveBirthsGroup_Women_act: MSMS0022_act
  PreviousLiveBirthsGroup_Women_prov: MSMS0022_prov
  SkinToSkinContact1HourTerm_Babies_act: MSMS0023_act
  SkinToSkinContact1HourTerm_Babies_prov: MSMS0023_prov
  TotalBabies_Babies_act: MSMS0024_act
  TotalBabies_Babies_prov: MSMS0024_prov
  TotalBookings_Women_act: MSMS0025_act
  TotalBookings_Women_prov: MSMS0025_prov
  TotalDeliveries_Women_act: MSMS0026_act
  TotalDeliveries_Women_prov: MSMS0026_prov
  ApgarScore5TermGroup7_Babies_act: MSMS0027_act
  ApgarScore5TermGroup7_Babies_prov: MSMS0027_prov
  BirthweightTermGroup_Babies_act: MSMS0028_act
  BirthweightTermGroup_Babies_prov: MSMS0028_prov
  BirthweightTermGroup2500_Babies_act: MSMS0029_act
  BirthweightTermGroup2500_Babies_prov: MSMS0029_prov
  CO_Concentration_Delivery_Women_act: MSMS0030_act
  CO_Concentration_Delivery_Women_prov: MSMS0030_prov
  SmokingStatusGroupBooking_Women_act: MSMS0031_act
  SmokingStatusGroupBooking_Women_prov: MSMS0031_prov