from pyspark.sql.types import StructType, StructField, StringType

DIMENSIONS_SCHEMA = StructType([
    StructField("dimension_cohort_id",                  StringType(), nullable=False),
    StructField("metric_id",                            StringType(), nullable=False),
    StructField("AgeAtBookingMotherAvg",                StringType(), nullable=True),
    StructField("AgeAtBookingMotherGroup",              StringType(), nullable=True),
    StructField("ApgarScore5TermGroup7",                StringType(), nullable=True),
    StructField("BabyFirstFeedBreastMilkStatus",        StringType(), nullable=True),
    StructField("BirthweightTermGroup",                 StringType(), nullable=True),
    StructField("BirthweightTermGroup2500",             StringType(), nullable=True),
    StructField("CCP_Antenatal",                        StringType(), nullable=True),
    StructField("CCP_Any_Pathways",                     StringType(), nullable=True),
    StructField("CCP_Birth",                            StringType(), nullable=True),
    StructField("CCP_Postpartum",                       StringType(), nullable=True),
    StructField("CO_Concentration_Delivery",            StringType(), nullable=True),
    StructField("ComplexSocialFactorsInd",              StringType(), nullable=True),
    StructField("DeliveryMethodBabyGroup",              StringType(), nullable=True),
    StructField("DeprivationDecileAtBooking",           StringType(), nullable=True),
    StructField("EthnicCategoryMotherGroup",            StringType(), nullable=True),
    StructField("FolicAcidSupplement",                  StringType(), nullable=True),
    StructField("GestAgeFormalAntenatalBookingGroup",   StringType(), nullable=True),
    StructField("GestationLengthBirth",                 StringType(), nullable=True),
    StructField("GestationLengthBirthGroup37",          StringType(), nullable=True),
    StructField("PCP_Antenatal",                        StringType(), nullable=True),
    StructField("PCP_Any_Pathways",                     StringType(), nullable=True),
    StructField("PCP_Birth",                            StringType(), nullable=True),
    StructField("PCP_Postpartum",                       StringType(), nullable=True),
    StructField("PlaceTypeActualDeliveryMidwifery",     StringType(), nullable=True),
    StructField("PreviousCaesareanSectionsGroup",       StringType(), nullable=True),
    StructField("PreviousLiveBirthsGroup",              StringType(), nullable=True),
    StructField("SkinToSkinContact1HourTerm",           StringType(), nullable=True),
    StructField("SmokingStatusGroupBooking",            StringType(), nullable=True),
    StructField("TotalBabies",                          StringType(), nullable=True),
    StructField("TotalBookings",                        StringType(), nullable=True),
    StructField("TotalDeliveries",                      StringType(), nullable=True),
])
